# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AuthTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AppAuth', '>= 0.91'
  
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path

end
